M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Mon 25 Jul 2022 12:40:50 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-25T12:40:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X7.0455Y-3.5927
X7.0455Y-3.7896
T0
M30
